baseURL = 'https://teampointbarre.github.io'
languageCode = 'fr-fr'
title = '🌲 Team Point Barre'
theme = 'sapin'

[menu]
[[menu.main]]
  name = 'La méthode'
  pageRef = '/methode'
  weight = 20
[[menu.main]]
  name = 'Parole aux athlètes'
  pageRef = '/recits'
  weight = 40
[[menu.main]]
  name = 'Refuge'
  url = 'https://refuge.teampointbarre.fr'
  weight = 50

[params]
    description = "Site de la team point barre"
    dateFormatToUse = "01-01-2023"
    replaceGoogleFonts = "fonts.loli.net"

