baseURL = 'https://teampointbarre.github.io/hugo/'
languageCode = 'fr-fr'
title = '🌲 Team Point Barre'
theme = 'sapin'

[menu]
[[menu.main]]
  name = 'Accueil'
  pageRef = '/'
  weight = 10
[[menu.main]]
  name = 'La méthode'
  pageRef = '/methode'
  weight = 20
[[menu.main]]
  name = 'Derrière les sapins'
  pageRef = '/coachs'
  weight = 30
[[menu.main]]
  name = 'Parole aux athlètes'
  pageRef = '/recits'
  weight = 40
[[menu.main]]
  name = 'Refuge'
  url = '/'
  weight = 50

